apiVersion: v2
appVersion: "1.0"
description: A Helm chart for the Gaia-X self-description microservice
name: self-description
version: 1.0.0

#dependencies:
#  - name: common
#    version: 1.0.0
#    repository: file://../../common